#!/usr/bin/env python
# coding: utf-8

# In[1]:


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


# In[2]:


data = pd.read_csv(r"C:\Users\imins\Downloads\Add_sales_data_2018.csv")


# In[5]:


data.head()


# # 1. First of all, check whether there is any relationship between the amount spent for advertising through five different companies and profit generated.

# In[9]:


a = data[['Add1(in Thousands)','Add2(in Thousands)','Add3(in Thousands)','Add4(in Thousands)','Add5(in Thousands)','Profit(in Thousands)']]


# In[11]:


a.corr()


# In[10]:


crmtx=a.corr()
plt.subplots(figsize=(15,8))
sns.heatmap(crmtx,vmin=-1,vmax=1,annot=True,linewidths=0.2,cmap="YlGnBu")


# ##### Profit has a higher positive correlation with all 5 different ad companies

# In[ ]:





# # 2. Build a regression model to predict the profit from the given data and comment your findings on it

# In[112]:


from sklearn.linear_model import LinearRegression
x = data[['Add1(in Thousands)','Add2(in Thousands)','Add3(in Thousands)','Add4(in Thousands)','Add5(in Thousands)']]
y = data[['Profit(in Thousands)']]
model = LinearRegression().fit(x,y)


# In[113]:


model.score(x,y)


# In[99]:


r=model.coef_


# In[100]:


r


# In[101]:


l = model.predict(x)


# In[102]:


q = pd.DataFrame(l)


# In[72]:


q.rename(columns ={0:'Profit'},inplace = True)


# In[73]:


q


# # 3. Predict the profit generated by the company, if they wish to spend the following amount for advertisement.

# In[120]:


predictedprofit= model.predict([[290,312,309,298,320]])


# In[116]:


print('Predicted profit is',predictedprofit)

